version: '3.7'
services:
  security-markings:
    image: ${REGISTRY:-docker.io}/cnxta/ion-security-markings
    ports:
      - target: 8080
        published: 9040
        protocol: tcp
      - target: 10050
        published: 10050
        protocol: tcp
    networks:
      - transform
    deploy:
      restart_policy:
        condition: any
networks:
  transform:
    external: true